services:
  - type: web
    name: nailcare-pro-api
    env: node
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000